 
global:
  registry:
    address: 
Master:
  ServiceType: NodePort
  NodePort: 32001
  AdminPassword: "Jenkins12345"
  gitlabConfigs:
    - name: gn
      manageHooks: true
      serverUrl: gu
      token: gt
  Location:
    url: <Jenkins Location URL>
Persistence:
  Enabled: false
  Host:
    NodeName: 
    Path: /root/alauda/jenkins
AlaudaACP:
  Enabled: true
  JenkinsServiceName: "jenkins"
alaudapipelineplugin:
  consoleURL: ""
  apiEndpoint: ""
  apiToken: ""
  account: ""
  spaceName: ""
  clusterName: ""
  namespace: ""
AlaudaDevOpsCredentialsProvider:
  globalNamespaces: "cpaas-system-global-credentials,cpaas-system"
Erebus:
  Namespace: "cpaas-system"
  URL: "https://erebus.cpaas-system.svc.cluster.local:443/kubernetes"
 
